# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Next JS Pipeleine

on:
  push:
    branches: ["master"]

jobs:
  job1: 
    - name: This is Job1
      runs-on: ubuntu-latest
      steps:
        - name: First step - job1 
          run: echo "First step - job1"

        - name: Create a File 
          run: touch test.txt

  job2: 
    - name: This is Job3
      runs-on: ubuntu-latest
      steps:
        - name: Verify the file job2 
          run: ls -l